// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_NxWPIalfbOiDdTeKiwbGU3OjHKgM2HU',
    appId: '1:52230918996:web:54e6e37a70d438187aaec1',
    messagingSenderId: '52230918996',
    projectId: 'flashcard-28ad6',
    authDomain: 'flashcard-28ad6.firebaseapp.com',
    storageBucket: 'flashcard-28ad6.appspot.com',
    measurementId: 'G-65VBF65TG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm4eNJeQeDwIxnb7C3cdDUSW9Iz6b-vJQ',
    appId: '1:52230918996:android:51c081bf58cd29647aaec1',
    messagingSenderId: '52230918996',
    projectId: 'flashcard-28ad6',
    storageBucket: 'flashcard-28ad6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNDiL3IoAx02ixNzb6ZsUGW1gTYqLn6l4',
    appId: '1:52230918996:ios:4eb52a02f8d36c197aaec1',
    messagingSenderId: '52230918996',
    projectId: 'flashcard-28ad6',
    storageBucket: 'flashcard-28ad6.appspot.com',
    iosClientId: '52230918996-q8dqo04lnlgbve4lltvicq9na4vcrua5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashcard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNDiL3IoAx02ixNzb6ZsUGW1gTYqLn6l4',
    appId: '1:52230918996:ios:42a71598072091327aaec1',
    messagingSenderId: '52230918996',
    projectId: 'flashcard-28ad6',
    storageBucket: 'flashcard-28ad6.appspot.com',
    iosClientId: '52230918996-4cl45lu4oiqgdd29feo1catr557nmnoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashcard.RunnerTests',
  );
}
